### PR TITLE
check the return code of ::deflate for errors; handle the case where …

### LINKED ISSUE #125: Per-message deflate causes bad_alloc on message length of 0
The return code of `::deflate` is not checked  - it returns Z_BUF_ERROR when:

- It has already processed data before; and
- It is passed a buffer with a length of zero

This happens when sending a message (other than the first message) over a websocket with a size of 0.

Then, resizing the output vector to `size() - 4`, which is a huge number as `size()` is zero, throws a bad_alloc exception.

I believe following RFC 7692 7.2.1 to the letter would fix this:

```
   2.  If the resulting data does not end with an empty DEFLATE block
       with no compression (the "BTYPE" bits are set to 00), append an
       empty DEFLATE block with no compression to the tail end.
```

### PR DESCRIPTION
**Pull request by cake4289**
…inputLen == 0 by inserting an empty uncompressed block when not present

Fixes #125

### CODE REVIEW

File: src/main/c/seasocks/ZlibContext.cpp [hunk 1]
```diff
@@ -86,17 +86,27 @@ struct ZlibContext::Impl {
         deflateStream.next_in = (unsigned char*) input;
         deflateStream.avail_in = inputLen;
 
-        do {
+        if (inputLen > 0) do {
```
Comment (offa) [inline src/main/c/seasocks/ZlibContext.cpp]: This formatting is a bit confusing (at least for me). Especially "closing" the `if` with a `while`.

**Comment by offa** [comment]
Please let me know once you are ready and I'll merge this.

**Comment by cake4289** [comment]
Ok I'm done with my changes - but there are no tests covering compression currently. Should I add some? I've just been testing locally with an echo server.

**Comment by offa** [comment]
Tests are always welcome. However, in this case there aren't any so this shouldn't be a blocker for the PR.

If you can provide some tests, feel free to open another PR :-)
